# Generated by Django 3.2.8 on 2021-11-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=80, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=2000)),
            ],
        ),
    ]
